name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!

  deploy_test:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: FTP Deploy
      uses: fabeabe/git-sftp-action@1.1.1
      with:
        url: sftp://${{ secrets.WEB_HOST }}/MaeandtheKingdomsofSeasons/wp-content/themes/mae-and-the-kingdoms-of-seasons-test
        user: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        syncroot: ./wp-template/
        options: --dry-run --verbose --insecure --auto-init
      
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

 
