name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!

  deploy_test:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: Sync files
      run: |
        mkdir -p ~/.config/rclone
        cat .github/workflow/rclone.config | sed 's/[$]{host}/${{ secrets.WEB_HOST }}/' | sed 's/[$]{username}/${{ secrets.USERNAME }}/' > ~/.config/rclone/rclone.conf
        rclone config password remote pass "${{ secrets.PASSWORD }}"
        rclone rclone sync -i ./wp-template remote:MaeandtheKingdomsofSeasons/wp-content/themes/mae-and-the-kingdoms-of-seasons-test
      
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

 
